mysite/myauth/urls.py
from django.urls import path

from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    MyLoginView,
    AboutMeView,
    RegisterView,
    AboutMeUpdateView,
    ProfilesListView,
)


app_name = "myauth"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", MyLoginView.as_view(), name="login"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("", ProfilesListView.as_view(), name="profiles_list"),
    path("about-me/<int:pk>/", AboutMeView.as_view(), name="about-me"),
    path("about-me/<int:pk>/update/", AboutMeUpdateView.as_view(), name="profile_update"),
    path("cookie/get", get_cookie_view, name="cookie-get"),
    path("cookie/set", set_cookie_view, name="cookie-set"),
    path("session/get", get_session_view, name="session-get"),
    path("session/set", set_session_view, name="session-set"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

urlpatterns = [
    path('accounts/', include('myauth.urls')),
    path('blog/', include('blogapp.urls')),
    path(
            "sitemap.xml",
            sitemap,
            {"sitemaps": sitemaps},
            name="django.contrib.sitemaps.views.sitemap",
        ),
]

urlpatterns += i18n_patterns(
    path('shop/', include('shopapp.urls')),
    path('admin/', admin.site.urls),
    path('api/schema/', SpectacularAPIView.as_view(), name="schema"),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name="swagger"),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name="redoc"),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/shopapp/urls.py
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from .views import (
    ShopIndexView,
    ProductsListView,
    ProductDetailsView,
    OrdersListView,
    OrderDetailView,
    OrderCreateView,
    OrderDeleteView,
    OrderUpdateView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ProductsDataExportView,
    OrderDataExportView,
    ProductViewSet,
    OrderViewSet,
    LatestProductsFeed,
    UserOrdersListView,
    OrderCacheExportView,
)

app_name = "shopapp"

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)


urlpatterns = [
    path("", ShopIndexView.as_view(), name="shop_index"),
    path("api/", include(routers.urls)),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/export/", ProductsDataExportView.as_view(), name="products-export"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/archive/", ProductDeleteView.as_view(), name="product_delete"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/latest/feed/", LatestProductsFeed(), name="products-feed"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_details"),
    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path("orders/export", OrderDataExportView.as_view(), name="orders-export"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/<int:pk>/confirm-delete/", OrderDeleteView.as_view(), name="order_delete"),
    path("orders/<int:pk>/confirm-update/", OrderUpdateView.as_view(), name="order_update"),
    path("users/<int:user_id>/orders/", UserOrdersListView.as_view(), name="user_orders"),
    path("users/<int:user_id>/orders/export", OrderCacheExportView.as_view(), name="orders-export-cached"),
]

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


def product_preview_directory(instance: "Product", filename: str) -> str:
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):
    class Meta:
        ordering = ["name", "price"]
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    name = models.CharField(max_length=100, verbose_name=_("Name"))
    description = models.TextField(null=False, blank=True, verbose_name=_("Description"))
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2, verbose_name=_("Price"))
    discount = models.SmallIntegerField(default=0, verbose_name=_("Discount"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Created at"))
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name=_("Created by"))
    archived = models.BooleanField(default=False, verbose_name=_("Archived"))
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory, verbose_name=_("Preview"))

    def __str__(self):
        return f"Product(pk={self.pk}, name={self.name!r})"

    def get_absolute_url(self):
        return reverse("shopapp:product_details", kwargs={"pk": self.pk})


def product_images_directory_path(instance: "ProductImage", filename: str) -> str:
    return "products/product_{pk}/images/{filename}".format(
        pk=instance.product.pk,
        filename=filename,
    )


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images", verbose_name=_("Product"))
    image = models.ImageField(upload_to=product_images_directory_path, verbose_name=_("Image"))
    description = models.CharField(max_length=200, null=False, blank=True, verbose_name=_("Description"))


class Order(models.Model):
    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    delivery_address = models.TextField(null=True, blank=True, verbose_name=_("Delivery address"))
    promocode = models.CharField(max_length=20, null=False, blank=True, verbose_name=_("Promocode"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Created at"))
    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name=_("User"))
    products = models.ManyToManyField(Product, related_name="orders", verbose_name=_("Products"))

mysite/shopapp/forms.py
from django import forms
from .models import Product, Order
from django.contrib.auth.models import Group


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name", "price", "description", "discount", "preview",

    images = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={"multiple": True}),
    )


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "delivery_address", "promocode", "products", "user"


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name']


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

mysite/shopapp/views.py
from csv import DictWriter
from timeit import default_timer
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin, LoginRequiredMixin
from django.core.cache import cache
from django.shortcuts import reverse
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.request import Request
from rest_framework.decorators import action
from .models import Product, Order, ProductImage, User
from .forms import ProductForm
from rest_framework.viewsets import ModelViewSet
from .serializers import ProductSerializer, OrderSerializer
from django.contrib.syndication.views import Feed


class ShopIndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        links = [
            {"title": "Products", "address": "products/"},
            {"title": "Orders", "address": "orders/"},
        ]
        context = {
            "time_running": default_timer(),
            "links": links
        }
        return render(request, 'shopapp/shop-index.html', context=context)


class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = [
        DjangoFilterBackend,
        OrderingFilter,
    ]
    filterset_fields = [
        "delivery_address",
        "promocode",
        "created_at",
        "user",
        "products",
    ]
    ordering_fields = [
        "user",
        "created_at",
    ]

    @action(methods=["get"], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type="text/csv")
        filename = "orders-export.csv"
        response["Content-Disposition"] = f"attachment; filename={filename}"
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            "delivery_address",
            "promocode",
            "created_at",
            "user_id",
            "products",
        ]
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for order in queryset:
            writer.writerow({
                field: getattr(order, field)
                for field in fields
            })
        return response


class ProductViewSet(ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        OrderingFilter,
    ]
    search_fields = ["name", "description"]
    ordering_fields = [
        "name",
        "price",
        "discount",
    ]


class ProductDetailsView(DetailView):
    template_name = "shopapp/products-details.html"
    queryset = Product.objects.prefetch_related("images")
    context_object_name = "product"


class ProductsListView(ListView):
    template_name = 'shopapp/products-list.html'
    # model = Product
    context_object_name = "products"
    queryset = (
        Product.objects.filter(archived=False)
        .filter(created_at__isnull=False)
        .order_by("-created_at")
    )


class ProductCreateView(PermissionRequiredMixin, CreateView):
    permission_required = "shopapp.add_product"
    model = Product
    fields = "name", "price", "description", "discount", "preview"
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        form.instance.created_by_id = self.request.user.id
        return super().form_valid(form)


class ProductUpdateView(PermissionRequiredMixin, UserPassesTestMixin, UpdateView):
    permission_required = "shopapp.change_product"
    model = Product
    # fields = "name", "price", "description", "discount", "preview"
    form_class = ProductForm
    template_name_suffix = "_update_form"

    def test_func(self):
        return self.request.user.id == self.get_object().created_by_id or self.request.user.is_superuser

    def get_success_url(self):
        return reverse(
            "shopapp:product_details",
            kwargs={"pk": self.object.pk},
        )

    def form_valid(self, form):
        response = super().form_valid(form)
        for image in form.files.getlist("images"):
            ProductImage.objects.create(
                product=self.object,
                image=image,
            )
        return response


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class ProductsDataExportView(View):
    def get(self, requets: HttpRequest) -> JsonResponse:
        products = Product.objects.order_by("pk").all()
        products_data = [
            {
                "pk": product.pk,
                "name": product.name,
                "price": product.price,
                "archived": product.archived,
            }
            for product in products
        ]
        return JsonResponse({"products": products_data})


class LatestProductsFeed(Feed):
    title = "Shop products (latest)"
    description = "Updates on changes and addition products"
    link = reverse_lazy("shopapp:products_list")

    def items(self):
        return (
            Product.objects
            .select_related("created_by")
            .prefetch_related("images")
            .filter(created_at__isnull=False)
            .order_by("-created_at")[:5]
        )

    def item_title(self, item: Product):
        return item.name

    def item_description(self, item: Product):
        return item.description[:200]


class OrdersListView(ListView):
    queryset = (
        Order.objects
        .select_related("user")
        .prefetch_related("products")
    )


class OrderDetailView(PermissionRequiredMixin, DetailView):
    permission_required = "shopapp.view_order"
    queryset = (
        Order.objects
        .select_related("user")
        .prefetch_related("products")
    )


class OrderCreateView(CreateView):
    model = Order
    fields = "user", "products", "promocode", "delivery_address"
    success_url = reverse_lazy("shopapp:orders_list")


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy("shopapp:orders_list")


class OrderUpdateView(UpdateView):
    model = Order
    fields = "user", "products", "promocode", "delivery_address"
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            "shopapp:order_details",
            kwargs={"pk": self.object.pk},
        )


class OrderDataExportView(View, UserPassesTestMixin):

    def test_func(self):
        return self.request.user.is_staff

    def get(self, request: HttpRequest) -> JsonResponse:
        orders = Order.objects.order_by("pk").all()
        orders_data = [
            {
                "pk": order.pk,
                "address": order.delivery_address,
                "promocode": order.promocode,
                "user": order.user.id,
                "products": [product.id for product in order.products.all()]
            }
            for order in orders
        ]
        return JsonResponse({"orders": orders_data})


class UserOrdersListView(LoginRequiredMixin, ListView):
    template_name = "shopapp/user_orders.html"

    def get_queryset(self, owner=None, **kwargs):
        self.owner = get_object_or_404(User, pk=self.kwargs['user_id'])
        return Order.objects.select_related('user').prefetch_related('products').filter(user_id=self.owner)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['owner'] = self.owner
        return context


class OrderCacheExportView(View, UserPassesTestMixin):

    def test_func(self):
        return self.request.user.is_staff

    def get(self, request: HttpRequest, **kwargs) -> JsonResponse:
        user_id = get_object_or_404(User, pk=self.kwargs['user_id'])
        print(user_id)
        cache_key = user_id
        orders_data = cache.get(cache_key)
        orders = Order.objects.filter(user_id=user_id).order_by("pk")
        if orders_data is None:
            orders_data = [
                {
                    "pk": order.pk,
                    "address": order.delivery_address,
                    "promocode": order.promocode,
                    "user": order.user.id,
                    "products": [product.id for product in order.products.all()]
                }
                for order in orders
            ]
            cache.set(cache_key, orders_data, 3000)
        return JsonResponse({"orders": orders_data})

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
        Base body
    {% endblock %}

    {% now 'H:i' %}
    <div>
        {% now 'l' as current_weekday %}
        Today is {{current_weekday}}
    </div>

</body>
</html>

mysite/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create a new product</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}

            <button type="submit">Create</button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:products_list' %}">
            Back to products list
        </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm Archive {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to delete {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}"
        >Back to order</a>
    </div>
    <br>
    <div>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Delete</button>
      </form>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders # {{ object.pk }} details
{% endblock %}

{% block body %}
    <h1>Orders # {{ object.pk }}</h1>
        <div>
            <p>Order by: {% firstof object.user.first_name object.user.username %}</p>
            <p>Promocode: <code>{{ object.promocode }}</code></p>
            <p>Delivery address: {{ object.delivery_address }}</p>
            <div>
                Products in order:
                <ul>
                    {% for product in order.products.all %}
                        <li>{{ product.name }} for ${{product.price}}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    <div>
        <a href="{% url 'shopapp:order_update' pk=order.pk %}">Update order</a>
    </div>
    <div>
        <a href="{% url 'shopapp:order_delete' pk=order.pk %}">Delete order</a>
    </div>
    <div>
        <a href="{% url 'shopapp:orders_list' %}">Back to orders</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create order
{% endblock %}

{% block body %}
    <h1>Create order:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
                <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:orders_list' %}"
        >Back to orders list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1>Orders:</h1>
    {% if object_list %}
        <div>
        {% for order in object_list %}
            <div>
                <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">
                    Details # {{ order.pk }}</a></p>
                <p>Order by: {% firstof order.user.first_name order.user.username %}</p>
                <p>Promocode: <code>{{ order.promocode }}</code></p>
                <p>Delivery address: {{ order.delivery_address }}</p>
            </div>
                Products in order:
                <ul>
                    {% for product in order.products.all %}
                        <li>{{ product.name }} for ${{product.price}}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <h3>No orders yet</h3>
    {% endif %}

    <div>
        <a href="{% url 'shopapp:order_create' %}">
            Create a new order
        </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update product
{% endblock %}

{% block body %}
    <h1>Update order:</h1>
    <div>Update
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}"
        >Back to orders #{{ object.pk }}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/orders_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls %}
    <li>
        <a href="{% url 'admin:import_orders_csv' %}" class="addlink">
            Import CSV
        </a>
    </li>
    {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm Archive {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to Archive {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk %}"
        >Back to products</a>
    </div>
    <br>
    <div>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Archive</button>
      </form>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create product:</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}"
        >Back to products list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Product' %} #{{product.pk}}
{% endblock %}

{% block body %}
<h1>{% translate 'Product' %} <strong>{{ product.name }}</strong></h1>
<div>
    <div>{% translate 'Description' %}: <em>{{ product.description }}</em></div>
    <div>{% translate 'Price' %}: {{ product.price }}</div>
    <div>{% translate 'Discount' %}: {{ product.discount }}</div>
    <div>{% translate 'Archived' context 'Product status' %}: {{ product.archived }}</div>
    {% if product.preview %}
        <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
    {% endif %}
    <h3>{% translate 'Images' %}</h3>
    <div>
        {% if product.images.all|length != 0 %}
            {% blocktranslate count images_count=product.images.all|length %}
            There is only one image
            {% plural %}
            There are {{ images_count }} images
            {% endblocktranslate %}
        {% endif %}
    </div>
    <div>
        {% for img in product.images.all %}
            <div>
                <img src="{{img.image.url}}" alt="{{img.image.name}}">
                <div>{{ img.description }}</div>
            </div>
        {% empty %}
            <div>{% translate 'No images uploaded yet' %}</div>
        {% endfor %}
    </div>
</div>
<p>{% translate 'Created by' %}: {% firstof object.created_by.first_name object.created_by.username %}</p>
<div>
    <a href="{% url 'shopapp:product_update' pk=product.pk %}">{% translate 'Update product' %}</a>
</div>
<div>
    <a href="{% url 'shopapp:product_delete' pk=product.pk %}">{% translate 'Archive product' %}</a>
</div>
<div>
    <a href="{% url 'shopapp:products_list' %}"
    >{% translate 'Back to products list' %}</a>
</div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Products list' %}
{% endblock %}

{% block body %}
    <h1>{% translate 'Products' %}:</h1>
    {% if products %}
        <div>
            {% blocktranslate count product_count=products|length %}
                There is only one product
                {% plural %}
                There are {{ product_count }} products
            {% endblocktranslate %}
        </div>
        <div>
        {% for product in products %}
            <div>
                <p><a href="{% url 'shopapp:product_details' pk=product.pk %}">{% translate 'Name' context 'product name' %}: {{product.name}}</a></p>
                <p>{% translate 'Price' %}: {{product.price}}</p>
                {% translate 'no discount' as no_discount %}
                <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>
                {% if product.preview %}
                    <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                {% endif %}
            </div>
        {% endfor %}
        </div>
    {% if 'shopapp.add_product' in perms %}
    <div>
        <a href="{% url 'shopapp:product_create' %}">
            {% translate 'Create a new product' %}
        </a>
    </div>
    {% endif %}
    {% else %}
        {% url 'shopapp:product_create' as create_product_url %}
        {% blocktranslate %}
        <h3>No products yet</h3>
        <a href="{{ create_product_url }}"
            >Create a new one</a>
        {% endblocktranslate %}
    {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Shop index
{% endblock %}

{% block body %}
    <h1> Список доступных страниц </h1>
    <div>
        <ul>
            {% for link in links %}
                <li><a href={{link.address}}>{{link.title}}</a></li>
            {% empty %}
                No links here
            {% endfor %}
        </ul>
    </div>
    <div>
        Time running: {{time_running}}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/user_orders.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1>The user {{ owner }} made an order(s):</h1>
    {% if object_list %}
    {% cache 300 userinfo owner.pk %}
        <div>
        {% for order in object_list %}
            <div>
                <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">
                    Details # {{ order.pk }}</a></p>
                <p>Order by: {% firstof order.user.first_name order.user.username %}</p>
                <p>Promocode: <code>{{ order.promocode }}</code></p>
                <p>Delivery address: {{ order.delivery_address }}</p>
            </div>
                Products in order:
                <ul>
                    {% for product in order.products.all %}
                        <li>{{ product.name }} for ${{product.price}}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endfor %}
        </div>
    {% endcache %}
    {% else %}
        <h3>The user has no orders yet</h3>
    {% endif %}

    <div>
        <a href="{% url 'shopapp:order_create' %}">
            Create a new order
        </a>
    </div>
{% endblock %}