mysite/myauth/urls.py
from django.urls import path

from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    MyLoginView,
    AboutMeView,
    RegisterView,
    AboutMeUpdateView,
    ProfilesListView,
)


app_name = "myauth"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", MyLoginView.as_view(), name="login"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("", ProfilesListView.as_view(), name="profiles_list"),
    path("about-me/<int:pk>/", AboutMeView.as_view(), name="about-me"),
    path("about-me/<int:pk>/update/", AboutMeUpdateView.as_view(), name="profile_update"),
    path("cookie/get", get_cookie_view, name="cookie-get"),
    path("cookie/set", set_cookie_view, name="cookie-set"),
    path("session/get", get_session_view, name="session-get"),
    path("session/set", set_session_view, name="session-set"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

urlpatterns = [
    path('accounts/', include('myauth.urls')),
    path('blog/', include('blogapp.urls')),
    path(
            "sitemap.xml",
            sitemap,
            {"sitemaps": sitemaps},
            name="django.contrib.sitemaps.views.sitemap",
        ),
]

urlpatterns += i18n_patterns(
    path('shop/', include('shopapp.urls')),
    path('admin/', admin.site.urls),
    path('api/schema/', SpectacularAPIView.as_view(), name="schema"),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name="swagger"),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name="redoc"),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models


def avatar_directory(instance: "Profile", filename: str) -> str:
    return "accounts/user_{pk}/avatar/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=avatar_directory)

mysite/myauth/forms.py
from django import forms
from django.contrib.auth.models import User
from django.views.generic.edit import FormMixin

from .models import Profile


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = "email", "first_name", "last_name",


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = "agreement_accepted", "bio", "avatar"

    # email = forms.CharField()
    # first_name = forms.CharField()
    # last_name = forms.CharField()

mysite/myauth/views.py
import copy
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView, LoginView
from django.http import HttpRequest, HttpResponse
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, CreateView, UpdateView, ListView, DetailView
from .models import Profile
from .forms import ProfileForm, UserForm


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(
            self.request,
            username=username,
            password=password
        )
        login(request=self.request, user=user)
        return response


class AboutMeView(DetailView):
    template_name = "myauth/about-me.html"
    queryset = User.objects.all()


class MyLoginView(LoginView):
    template_name = 'myauth/login.html'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse(
                "myauth:about-me",
                kwargs={'pk': self.request.user.id},
            )


class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")


class AboutMeUpdateView(UserPassesTestMixin, UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name_suffix = "_update_form"

    def test_func(self):
        return self.request.user.is_staff or self.request.user.id == self.get_object().user.id

    def get_success_url(self):
        return reverse(
            "myauth:about-me",
            kwargs={'pk': self.get_object().user.id},
        )


class ProfilesListView(ListView):
    template_name = 'myauth/profiles-list.html'
    context_object_name = "users"
    queryset = User.objects.prefetch_related()


def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response


def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default value")
    return HttpResponse(f"Cookie value: {value!r}")


def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse("Session set!")


def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "default")
    return HttpResponse(f"Session value: {value!r}")

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}

{% block title %}
  About me
{% endblock %}

{% block body %}
<h1>User info</h1>
{% if user.is_authenticated %}
    <h2>Detail</h2>
    <p>Username: {{user.username}}</p>
    <p>First name: {{user.first_name}}</p>
    <p>Last name: {{user.last_name}}</p>
    <p>Email: {{user.email}}</p>
    <p>Bio: {{user.profile.bio}}</p>
    {% if user.profile.avatar %}
        <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}">
    {% else %}
        <h2>No avatar yet</h2>
    {% endif %}
{% else %}
    <h2>User is anonymous</h2>
{% endif %}
{% if request.user.is_staff or user.pk == request.user.id %}
    <div>
        <a href="{% url 'myauth:profile_update' pk=user.profile.pk %}">Update profile</a>
    </div>
{% endif %}
<div>
    <a href="{% url 'myauth:profiles_list' %}"
    >Back to profile list</a>
</div>
<div>
    <a href="{% url 'myauth:logout'%}">Logout</a>
</div>
{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

    {% endblock %}</title>
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
  Login
{% endblock %}

{% block body %}
<form method="post">
  {% csrf_token %}

  {{ form.as_p }}
  
  <button type="submit">Login</button>
</form>
{% endblock %}

mysite/myauth/templates/myauth/profile_update_form.html
{% extends 'myauth/base.html' %}

{% block title %}
    Update profile
{% endblock %}

{% block body %}
    <h1>Update profile: {% firstof object.user.username  object.user.first_name %}</h1>
    <div>Update
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <div>
        <a href="{% url 'myauth:about-me' pk=user.pk %}"
        >Back to my profile </a>
    </div>
{% endblock %}

mysite/myauth/templates/myauth/profiles-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Products list
{% endblock %}

{% block body %}
    <h1>Profiles:</h1>
    {% if users %}
        <div>
        {% for user in users %}
            <div>
                <h2><a href="{% url 'myauth:about-me' pk=user.pk %}">Name: {{user.username}}</a></h2>
                <p>Bio: {{user.profile.bio}}</p>
                <p>E-mail: {{user.email}}</p>
                {% if user.profile.avatar %}
                    <a href="{% url 'myauth:about-me' pk=user.pk %}"><img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}"></a>
                {% else %}
                    <h3>No avatar yet</h3>
                {% endif %}
            </div>
        {% endfor %}
        </div>
    {% else %}
        <h3>No profiles yet</h3>
    {% endif %}
    <div>
        <a href="{% url 'myauth:register' %}">
            Register new user
        </a>
    </div>


{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
  Register
{% endblock %}

{% block body %}
  <h1>Register</h1>
  <form method="post">
  {% csrf_token %}
  {{ form.as_p }}
    <input type="submit" value="Register">
  </form>
{% endblock %}