mysite/blogapp/urls.py
from django.urls import path
from .views import ArticlesListView, CreateArticleView, ArticleDetailView

app_name = "blogapp"

urlpatterns = [
    path("", ArticlesListView.as_view(), name="articles_list"),
    path("<int:pk>/", ArticleDetailView.as_view(), name="article_details"),
    path("create/", CreateArticleView.as_view(), name="create_article"),
]

mysite/myauth/urls.py
from django.urls import path

from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    MyLoginView,
    AboutMeView,
    RegisterView,
    AboutMeUpdateView,
    ProfilesListView,
)


app_name = "myauth"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", MyLoginView.as_view(), name="login"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("", ProfilesListView.as_view(), name="profiles_list"),
    path("about-me/<int:pk>/", AboutMeView.as_view(), name="about-me"),
    path("about-me/<int:pk>/update/", AboutMeUpdateView.as_view(), name="profile_update"),
    path("cookie/get", get_cookie_view, name="cookie-get"),
    path("cookie/set", set_cookie_view, name="cookie-set"),
    path("session/get", get_session_view, name="session-get"),
    path("session/set", set_session_view, name="session-set"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

urlpatterns = [
    path('accounts/', include('myauth.urls')),
    path('blog/', include('blogapp.urls')),
    path(
            "sitemap.xml",
            sitemap,
            {"sitemaps": sitemaps},
            name="django.contrib.sitemaps.views.sitemap",
        ),
]

urlpatterns += i18n_patterns(
    path('shop/', include('shopapp.urls')),
    path('admin/', admin.site.urls),
    path('api/schema/', SpectacularAPIView.as_view(), name="schema"),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name="swagger"),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name="redoc"),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/blogapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Author(models.Model):
    """
    Модель представляет Автора создаваемых статей.

    """
    class Meta:
        verbose_name = "Author"
        verbose_name_plural = "Authors"

    name = models.CharField(max_length=100, verbose_name="name")
    bio = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return f"Name: {self.name!r}"


class Category(models.Model):
    """
    Модель представляет категории блога.
    Для первичного создания категорий перейдите в терминал и выполните команду 'python manage.py create_category'.
    """
    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    name = models.CharField(max_length=40, verbose_name="name")

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    Модель представляет тэги для блога.
    Для первичного создания тэгов перейдите в терминал и выполните команду 'python manage.py create_tags'.
    """
    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    name = models.CharField(max_length=20, verbose_name="name")

    def __str__(self):
        return self.name


class Article(models.Model):
    """
    Модель представляет статью для блога.
    """
    class Meta:
        verbose_name = "Article"
        verbose_name_plural = "Articles"

    title = models.CharField(max_length=200, verbose_name="title")
    content = models.TextField(max_length=500, blank=True, verbose_name="content")
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name="pub_date")
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name="author")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="category")
    tags = models.ManyToManyField(Tag, related_name="articles", verbose_name="tags")

mysite/blogapp/views.py
from django.urls import reverse_lazy
from .models import Article
from django.views.generic import ListView, CreateView, DetailView


class ArticlesListView(ListView):
    template_name = "blogapp/articles-list.html"
    context_object_name = "articles"
    queryset = (
        Article.objects
        .select_related("author", "category")
        .prefetch_related("tags")
    )


class ArticleDetailView(DetailView):
    queryset = (
        Article.objects
        .select_related("author")
        .prefetch_related("tags")
    )


class CreateArticleView(CreateView):
    model = Article
    fields = "title", "content", "author", "category", "tags",
    success_url = reverse_lazy("blogapp:articles_list")

mysite/blogapp/templates/blogapp/article_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Article # {{ object.pk }} details
{% endblock %}

{% block body %}
    <h1>Article # {{ object.pk }}</h1>
    <div>
        <p><b>Title: </b>{{article.title}}</p>
        <p><b>Content: </b>{{article.content}}</p>
    </div>
    <div>
        <h3>Author:</h3>
        <p>Name: {{article.author.name}}</p>
        <p>Bio: {{article.author.bio}}</p>
    </div>
    <div>
        <a href="{% url 'blogapp:articles_list' %}">Back to articles list</a>
    </div>

{% endblock %}

mysite/blogapp/templates/blogapp/article_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create article
{% endblock %}

{% block body %}
    <h1>Create message:</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url 'blogapp:articles_list' %}"
        >Back to articles list</a>
    </div>
{% endblock %}

mysite/blogapp/templates/blogapp/articles-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Articles list
{% endblock %}

{% block body %}
    <h1>Articles: </h1>
    {% if articles %}
        <div>
            {% for article in articles %}
                <div>
                    <p><a href="{% url 'blogapp:article_details' pk=article.pk %}">Name: {{article.title}}</a></p>
                    <p>Publication date: {{article.pub_date}}</p>
                    <p>Author: {{article.author.name}}</p>
                    <p>Category: {{article.category}}</p>
                    </div>
                    Tags:
                        <ul>
                            {% for tag in article.tags.all %}
                                <li>{{ tag.name }} </li>
                            {% endfor %}
                        </ul>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h3>No articles yet</h3>
    {% endif %}
    <div>
    <a href="{% url 'blogapp:create_article' %}">
        Create a new article
    </a>
    </div>
{% endblock %}

mysite/blogapp/templates/blogapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
        Base body
    {% endblock %}

    {% now 'H:i' %}
    <div>
        {% now 'l' as current_weekday %}
        Today is {{current_weekday}}
    </div>

</body>
</html>